spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.meli.ordermanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: ${SERVER_PORT:8080}